---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline-policy-manager-role
rules:
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - pipelinepolicies
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - pipelinepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - pipelinepolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - policyregistrations
  resourceNames:
  - PipelinePolicy
  verbs:
  - register
