//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActionMethodSpec) DeepCopyInto(out *ActionMethodSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActionMethodSpec.
func (in *ActionMethodSpec) DeepCopy() *ActionMethodSpec {
	if in == nil {
		return nil
	}
	out := new(ActionMethodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePolicy) DeepCopyInto(out *PipelinePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePolicy.
func (in *PipelinePolicy) DeepCopy() *PipelinePolicy {
	if in == nil {
		return nil
	}
	out := new(PipelinePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePolicyList) DeepCopyInto(out *PipelinePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PipelinePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePolicyList.
func (in *PipelinePolicyList) DeepCopy() *PipelinePolicyList {
	if in == nil {
		return nil
	}
	out := new(PipelinePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipelinePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePolicySpec) DeepCopyInto(out *PipelinePolicySpec) {
	*out = *in
	in.TargetRef.DeepCopyInto(&out.TargetRef)
	if in.ActionMethods != nil {
		in, out := &in.ActionMethods, &out.ActionMethods
		*out = make([]ActionMethodSpec, len(*in))
		copy(*out, *in)
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = make([]RequestActionSpec, len(*in))
		copy(*out, *in)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = make([]ResponseActionSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePolicySpec.
func (in *PipelinePolicySpec) DeepCopy() *PipelinePolicySpec {
	if in == nil {
		return nil
	}
	out := new(PipelinePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipelinePolicyStatus) DeepCopyInto(out *PipelinePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipelinePolicyStatus.
func (in *PipelinePolicyStatus) DeepCopy() *PipelinePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PipelinePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestActionSpec) DeepCopyInto(out *RequestActionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestActionSpec.
func (in *RequestActionSpec) DeepCopy() *RequestActionSpec {
	if in == nil {
		return nil
	}
	out := new(RequestActionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseActionSpec) DeepCopyInto(out *ResponseActionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseActionSpec.
func (in *ResponseActionSpec) DeepCopy() *ResponseActionSpec {
	if in == nil {
		return nil
	}
	out := new(ResponseActionSpec)
	in.DeepCopyInto(out)
	return out
}
